### ISSUE TITLE
Changing number of states does not change model fitting

### ISSUE THREAD

**Issue by cmazzio** [abuzarmahmood/pytau#34]
Changing states to 3 produces model fitting with 4 states:

![Screenshot from 2024-06-02 13-37-21](https://github.com/abuzarmahmood/pytau/assets/143443066/8b0fb4ba-7510-49a6-950e-1ebaef988ec3)

**Comment by abuzarmahmood** [comment]
Could you please add where you changed number of states and what code you ran to fit the models and generate the plots?

**Comment by cmazzio** [comment]
I rat fit_with_fit_handler.py and changed only the states variable to 3

**Comment by abuzarmahmood** [comment]
Could you please attach the updated scripts you used here. Thanks.

**Comment by abuzarmahmood** [comment]
Issue selecting correct model

https://github.com/abuzarmahmood/pytau/blob/d0a2d6e697579bc934ae802a26a41fd2fa059e33/pytau/how_to/scripts/fit_with_fit_handler.py#L57C1-L61C49

```
dframe = fit_database.fit_database
wanted_exp_name = 'pytau_test'
wanted_frame = dframe.loc[dframe['exp.exp_name'] == wanted_exp_name] 
# Pull out a single data_directory
pkl_path = wanted_frame['exp.save_path'].iloc[0]
```

Plots came out fine once correct model was selected.
